

#ifndef _UI_DEFS
#define _UI_DEFS

#define _SET_PATCH_DIALOG_OPEND_BY_NONE				-1
#define _SET_PATCH_DIALOG_OPEND_BY_MAIN				0
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_1		1
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_2		2
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_3		3
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_4		4
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_5		5
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_6		6
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_7		7
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_8		8
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_9		9
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_10		10
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_11		11
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_12		12
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_13		13
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_14		14
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_15		15
#define _SET_PATCH_DIALOG_OPEND_BY_PROGRAM_16		16


#endif